---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: '12'

platforms:
  - name: centos-7.1
    driver:
      network:
      - ["forwarded_port", {guest: 4444, host: 4444}]

  - name: ubuntu-14.04
    driver:
      network:
      - ["forwarded_port", {guest: 4444, host: 4445}]

  - name: windows-2012r2
    driver:
      box: dhoer/windows-2012r2
      network:
      - ["forwarded_port", {guest: 4444, host: 4446}]
    attributes:

suites:
  - name: default
    run_list:
      - selenium_test::package_update
      - selenium_test::package
      - selenium_test::hub
      - selenium_test::node
      - selenium_test::screenresolution
    attributes:
      mozilla_firefox:
        32bit_only: true
